modLoader = "javafml"
loaderVersion = "${neoforge_loader_version_range}"
#issueTrackerURL = ""
license = "${license}"

[[mods]]
modId = "biomeblends"
version = "${version}"
displayName = "Biome Blends"
authors = "PiotrO15"
description = '''
Biome Blends are a new way to change the biome in a specified location. Great for players and modpack creators!
'''
logoFile = "icon.png"

[[dependencies.biomeblends]]
modId = "neoforge"
type = "required"
versionRange = "[26.1.2, 26.2)"
ordering = "NONE"
side = "BOTH"

[[dependencies.biomeblends]]
modId = "minecraft"
type = "required"
versionRange = "[26.1.2, 26.2)"
ordering = "NONE"
side = "BOTH"
